# -*- coding: utf-8 -*-
"""Automated_XRD._Gaussian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aX9h1Gw-PFxL8liRa9s7n13ocPg52YW4
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse
from scipy.sparse.linalg import spsolve
from scipy.ndimage import gaussian_filter1d

# =========================================================================
# 1. MEMBACA & PRE-PROCESSING DATA (ZERO-LEVEL SHIFT)
# =========================================================================
file_excel = '~/filepath/filename.xlsx'  # Ganti dengan path file Excel XRD kamu

if os.path.exists(file_excel):
    print(f"Membaca file data XRD: {file_excel} ...")
    data_excel = pd.read_excel(file_excel)
    twoTheta = data_excel.iloc[:, 0].to_numpy(dtype=float)
    Intensity = data_excel.iloc[:, 1].to_numpy(dtype=float)
else:
    print(f"File '{file_excel}' tidak ditemukan. Menggunakan data SIMULASI dengan drift negatif...")
    twoTheta = np.linspace(15, 70, 1100)
    I_amorf = 80.0 * np.exp(-((twoTheta - 22.0) / 4.5) ** 2)
    I_cryst = (
        45.0 * np.exp(-((twoTheta - 17.2) / 0.4) ** 2) +
        20.0 * np.exp(-((twoTheta - 20.2) / 0.3) ** 2) +
        22.0 * np.exp(-((twoTheta - 22.5) / 0.3) ** 2) +
        18.0 * np.exp(-((twoTheta - 23.7) / 0.3) ** 2) +
        15.0 * np.exp(-((twoTheta - 26.3) / 0.4) ** 2) +
        80.0 * np.exp(-((twoTheta - 32.1) / 0.4) ** 2) +
        75.0 * np.exp(-((twoTheta - 34.7) / 0.45) ** 2) +
        160.0 * np.exp(-((twoTheta - 36.6) / 0.5) ** 2) +
        12.0 * np.exp(-((twoTheta - 39.1) / 0.4) ** 2) +
        30.0 * np.exp(-((twoTheta - 57.0) / 0.4) ** 2)
    )
    drift = -100.0 * (1.0 / (1.0 + np.exp(-(twoTheta - 42.0) / 5.0)))  # Drift ke negatif
    noise = 3.0 * np.random.randn(len(twoTheta))
    Intensity = I_amorf + I_cryst + drift + noise

# A. ZERO-LEVEL OFFSET RESTORATION (Mengangkat spektrum ke I >= 0 secara fisis)
min_raw_val = np.min(Intensity)
if min_raw_val < 0:
    I_raw_shifted = Intensity - min_raw_val
else:
    I_raw_shifted = np.copy(Intensity)

# B. GAUSSIAN SMOOTHING
span_sigma = max(1.0, (0.01 * len(I_raw_shifted)) / 2.355)
I_smooth = gaussian_filter1d(I_raw_shifted, sigma=span_sigma)

# =========================================================================
# 2. BASELINE AMORF (ASYMMETRIC LEAST SQUARES / ALS)
# =========================================================================
def als_baseline(y, lam=1e5, p=0.002, niter=15):
    """
    Ekstraksi baseline amorf menggunakan Asymmetric Least Squares (ALS)
    """
    L = len(y)
    D = sparse.diags([1, -2, 1], [0, 1, 2], shape=(L - 2, L), format='csc')
    H = lam * (D.T @ D)
    w = np.ones(L)

    for _ in range(niter):
        W = sparse.diags(w, 0, shape=(L, L), format='csc')
        Z = W + H
        z = spsolve(Z, w * y)
        w = p * (y > z) + (1.0 - p) * (y <= z)
    return z

print("Menghitung baseline amorf menggunakan ALS...")
I_amorphous = als_baseline(I_smooth, lam=1e5, p=0.002, niter=15)
I_amorphous = np.minimum(I_amorphous, I_smooth)
I_amorphous = np.maximum(0, I_amorphous)
I_crystalline = np.maximum(0, I_smooth - I_amorphous)

# =========================================================================
# 3. KALKULASI PERSEN KRISTALINITAS (CI %)
# =========================================================================
trapz_func = getattr(np, 'trapezoid', getattr(np, 'trapz', None))
area_cryst = trapz_func(I_crystalline, twoTheta)
area_amorf = trapz_func(I_amorphous, twoTheta)
CI = (area_cryst / (area_cryst + area_amorf)) * 100.0

# =========================================================================
# 4. DETEKSI PUNCAK & PERSAMAAN SCHERRER
# =========================================================================
K = 0.9           # Faktor bentuk kristal
lambda_xrd = 0.15406  # Panjang gelombang Cu-Kalpha (nm)
max_cryst = np.max(I_crystalline)
min_height = max_cryst * 0.04

# Deteksi puncak lokal (Local Maxima)
cond = (
    (I_crystalline[1:-1] > I_crystalline[:-2]) &
    (I_crystalline[1:-1] > I_crystalline[2:]) &
    (I_crystalline[1:-1] >= min_height)
)
locs_idx = np.where(cond)[0] + 1
pks = I_crystalline[locs_idx]
numPeaks = len(pks)

fitResults = []

for i in range(numPeaks):
    idx = locs_idx[i]
    x0 = twoTheta[idx]

    # FWHM Calculation
    half_h = pks[i] / 2.0
    l_candidates = np.where(I_crystalline[:idx + 1] <= half_h)[0]
    r_candidates = np.where(I_crystalline[idx:] <= half_h)[0]

    if len(l_candidates) > 0 and len(r_candidates) > 0:
        l_idx = l_candidates[-1]
        r_idx = idx + r_candidates[0]
        fwhm_deg = twoTheta[r_idx] - twoTheta[l_idx]
    else:
        fwhm_deg = 0.4

    theta_rad = np.deg2rad(x0 / 2.0)
    beta_rad = np.deg2rad(fwhm_deg)
    D_size_nm = (K * lambda_xrd) / (beta_rad * np.cos(theta_rad))

    fitResults.append({
        'peak_number': i + 1,
        'center_2theta': x0,
        'fwhm_deg': fwhm_deg,
        'height': pks[i],
        'crystallite_size_nm': D_size_nm
    })

# =========================================================================
# 5. VISUALISASI MATPLOTLIB (SMART HYBRID ANNOTATION)
# =========================================================================
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 8.5), dpi=100)
fig.canvas.manager.set_window_title('XRD Analysis - Smart Hybrid Annotation')

# --- Subplot 1: Profil Total, Amorf, & Area Kristalin ---
ax1.plot(twoTheta, I_raw_shifted, color='lightgray', linewidth=0.9, label='Data Mentah (Shifted)')
ax1.plot(twoTheta, I_smooth, 'k-', linewidth=1.2, label='Smoothed Data')
ax1.plot(twoTheta, I_amorphous, 'r-', linewidth=2.0, label='Amorphous Baseline')

ax1.fill_between(twoTheta, I_amorphous, I_smooth, color='#33b249', alpha=0.25, label='Crystalline Area')

ax1.set_title(f'Analisis Kristalinitas | CI = {CI:.2f}% (Ac = {area_cryst:.1f}, Aa = {area_amorf:.1f})',
              fontsize=12, fontweight='bold')
ax1.set_xlabel(r'2$\theta$ (derajat)', fontweight='bold')
ax1.set_ylabel('Intensitas (a.u.)', fontweight='bold')
ax1.set_xlim(np.min(twoTheta), np.max(twoTheta))
ax1.set_ylim(0, np.max(I_smooth) * 1.18)
ax1.grid(True, linestyle=':', alpha=0.6)
ax1.legend(loc='upper right', frameon=True)
ax1.tick_params(direction='in')

# --- Subplot 2: Profil Kristalin dengan Anotasi Adaptif ---
ax2.plot(twoTheta, I_crystalline, color='#00a000', linewidth=1.3, label=r'Profil Kristalin ($I_{cryst}$)')

if numPeaks > 0:
    peak_x = [p['center_2theta'] for p in fitResults]
    peak_y = [p['height'] for p in fitResults]
    ax2.plot(peak_x, peak_y, 'r.', markersize=7, label='Puncak Terdeteksi')

    # Ambang batas pemisah antara puncak tinggi dan rendah (35% dari peak max)
    high_peak_threshold = 0.35 * max_cryst

    # Ketinggian vertikal bertingkat (4-Tier) khusus untuk puncak rendah
    low_tier_levels = [0.18, 0.36, 0.54, 0.72]
    low_peak_count = 0

    for res in fitResults:
        x0 = res['center_2theta']
        h0 = res['height']
        d_nm = res['crystallite_size_nm']
        label_str = f"{x0:.2f}°\n({d_nm:.1f} nm)"

        if h0 >= high_peak_threshold:
            # =============================================================
            # A. PUNCAK TINGGI: Teks langsung di atas puncak (Tanpa Garis)
            # =============================================================
            ax2.text(x0, h0 + (max_cryst * 0.04), label_str,
                     fontsize=8.5, ha='center', va='bottom',
                     color='#0026bf', fontweight='bold')
        else:
            # =============================================================
            # B. PUNCAK RENDAH: Garis Penunjuk Bertingkat (4-Tier)
            # =============================================================
            low_peak_count += 1
            tier_idx = (low_peak_count - 1) % len(low_tier_levels)
            target_y = h0 + (max_cryst * low_tier_levels[tier_idx])

            # 1. Garis penunjuk putus-putus biru halus
            ax2.plot([x0, x0], [h0, target_y - max_cryst * 0.015],
                     color='#1a4cbf', linestyle=':', linewidth=1.0)
            ax2.plot(x0, target_y - max_cryst * 0.015,
                     marker='.', color='#1a4cbf', markersize=4)

            # 2. Teks informasi di ujung garis penunjuk
            ax2.text(x0, target_y, label_str,
                     fontsize=7.5, ha='center', va='bottom',
                     color='#1a4cbf', fontweight='bold')

    ax2.set_ylim(0, max_cryst * 1.35)

ax2.set_title('Deteksi Puncak & Ukuran Kristalit D (nm) [Smart Hybrid Annotation]',
              fontsize=12, fontweight='bold')
ax2.set_xlabel(r'2$\theta$ (derajat)', fontweight='bold')
ax2.set_ylabel('Intensitas (a.u.)', fontweight='bold')
ax2.set_xlim(np.min(twoTheta), np.max(twoTheta))
ax2.grid(True, linestyle=':', alpha=0.6)
ax2.legend(loc='upper right', frameon=True)
ax2.tick_params(direction='in')

plt.tight_layout()

# =========================================================================
# 6. CETAK HASIL KE TERMINAL / CONSOLE
# =========================================================================
print("\n" + "=" * 87)
print("                HASIL KRISTALINITAS & UKURAN KRISTAL (PERSAMAAN SCHERRER)")
print("=" * 87)
print(f"Crystallinity Index (CI) : {CI:.2f} %")
print(f"Area Kristalin (Ac)      : {area_cryst:.2f}")
print(f"Area Amorf (Aa)          : {area_amorf:.2f}")
print(f"Panjang Gelombang X-Ray  : {lambda_xrd:.5f} nm (Cu-Kα)")
print("-" * 87)
print(f"{'Peak #':<6} | {'2-Theta (deg)':<13} | {'FWHM (deg)':<10} | {'Height (a.u.)':<13} | {'Size D (nm)':<11} | {'Tipe Tampilan'}")
print("-" * 87)

high_peak_thresh = 0.35 * max_cryst
for res in fitResults:
    tipe_str = 'Puncak Tinggi (Direct Text)' if res['height'] >= high_peak_thresh else 'Puncak Rendah (Leader Line)'
    print(f"{res['peak_number']:6d} | {res['center_2theta']:13.2f} | {res['fwhm_deg']:10.3f} | {res['height']:13.1f} | {res['crystallite_size_nm']:11.1f} | {tipe_str}")

print("=" * 87 + "\n")

# Tampilkan grafik
plt.show()